### ISSUE TITLE
Apache reverse proxy to openShift/Rails host proxy

### ISSUE THREAD

**Issue by javadre** [zlogic/vogon#4]
Since, I am using openShift. I have another question.:
I am not sure if it is related to issues you have seen. But, now that I have Vogon running I want to use a Apache reverse proxy.  When I setup my proxy I get user is 

not allowed message in my Apache mod_proxy (ProxyPass) or errorlogs. 

My proxy can get to the Vogon login page but hangs and timesout after I login. But, after some more research. I figure this is a specific configuration for openShift. 

I am not running in the openShift cloud. But, I installed my own openShift locally.  Since the cloud works. I think maybe I am  missing some DNS configurations, but 

since I am not hosting this publically. I just want the reverse proxy to control the user access and forward login credentials to openShift and then to Vogon.  When I 

connect without the proxy, directly to my openShift server, Vogon works fine.  https://192.168.x.x:15080/vogon

Using the reverse Apache proxy:
However, after I forward the Apache proxy to openShift Vogon. I get user is not allowed after I put in the authenticated user. From my research this looks like a 

spring security that can not be bypassed and looks for the correct reverse user name from the Apache proxy -> openShift(rails env) -> to Vogon(spring instance).
I have researched source code a little, where there was a default login leonard nimoy using spring oauth2. 
http://sourceforge.net/p/vogonfinance/code/ci/3f4ea74715447952772e3eb19315803f702d6ae6/

But, even this login did not work. I know this is NOT a problem with the code but maybe Apache environment proxy configuration. Do you have any known solutions?. I 

think there is a openShift proxy module OAuth/spring module that may work with openShift. But, I really am not able to add another module as my install of openShift 

will not allow me to install more than one web module per instance. So, to use the module, I would have to install it on another new instance, and seperate it from 

Vogon.
# Here is the 3rd party module - I am thinking may help my reverse proxy work

https://www.npmjs.com/package/openshift-auth-proxy

Other details: I have setup http to forward all openShift traffic to -> https. on Vogon Tomcat since 2.1 Vogon forces use of https. I followed this, Per these 

instructions:

==================Details of me fixing https tomcat loop and forcing http -> https
https://developers.openshift.com/en/troubleshooting-faq.html

For Tomcat (JBoss EWS)

You can also use security-constraint directives in your web.xml file to force HTTPS connectivity, but your application will go into a Redirect Loop error. To resolve 

that, you need to do the following:

Update your repo/.openshift/config/server.xml file's Connector to look like:

<Connector address="${OPENSHIFT_JBOSSEWS_IP}"
           port="${OPENSHIFT_JBOSSEWS_HTTP_PORT}"
           protocol="HTTP/1.1"
           connectionTimeout="20000"
           redirectPort="443"/>

Then add a Valve directive to your repo/.openshift/config/context.xml file:

<Valve className="org.apache.catalina.valves.RemoteIpValve"
       protocolHeader="x-forwarded-proto" />

A sample security-constraint directive in repo/src/main/webapp/WEB-INF/web.xml looks like:

<security-constraint>
  <web-resource-collection>
    <url-pattern>/*</url-pattern>
  </web-resource-collection>
  <user-data-constraint>
    <transport-guarantee>CONFIDENTIAL</transport-guarantee>
  </user-data-constraint>
 </security-constraint>

Oauth2 and spring research:
=============================internet links oauth2/spring ==================
https://tools.ietf.org/html/rfc6749#section-4.3.2
http://www.btday.com/401-unauthorized-error-before-trying-to-get-access-token-in-spring-security-oauth-2/

Thanks
Andre

**Comment by zlogic** [comment]
Hi,

Could you tell me which Openshift version you're using (and which container)? Or provide a VM with your environment?

It's strange that this happens, because OAuth works well  and the only problems I had were when running in cloud environments where the reverse proxy only supported HTTP and not HTTPs. This way Spring Security forced a redirect from HTTP to HTTPS and the reverse proxy was unable to connect.

Reverse proxies themselves should never modify headers

You can enable full logging in 
[application.properties](/zlogic/vogon/tree/master/vogon-web/vogon-web-service/src/main/resources/application.properties) by uncommenting the `#logging.level.=DEBUG` line and rebuilding from source.

By the way, how are you trying to login? Default/Default is the login/password. If you're setting the username/password in the database, this may not work because Spring Security keeps the password hash only.

Or do you want Vogon to use Openshift's authentication instead of its private user database?
